name: CI C

on:
  push:
    paths:
      - "c_app/**"
      - ".github/workflows/ci-c.yml"
    paths-ignore:
      - "README.md"
  pull_request:
    paths:
      - "c_app/**"
    

jobs:
  c-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update && sudo apt-get install -y gcc
      - run: gcc c_app/main.c -o c_app/programa
      - run: ./c_app/programa
