name: CI Python

on:
  push:
    paths:
      - "python_app/**"
      - ".github/workflows/ci-python.yml"
  pull_request:
    paths:
      - "python_app/**"

jobs:
  python-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - run: python python_app/hello.py
